development:
  # privacy
  #   true: units/items are available to logged in users only (token required)
  #   false:
  #       units/items where is_public == true are available to public (no token)
  #       locations are available to unregistered users
  #   custom:
  #       public units are available to unregistered users
  #       private units may be accessible to certain users based on user_access table
  #       locations are available to unregistered users
  privacy: false

  # localization
  #   true:
  #     only units in the same location/network as user may be accessed. user location/network based on last checkin/ last login ip.
  #     only logged in users may view units regardless of value of privacy variable
  #   false: units are visible regardless of user location
  localization: false


  # localization type
  #   location:
  #     only units in the same location as user may be accessed. user location based on last checkin.
  #     only logged in users may view units regardless of value of privacy variable
  #   network:
  #     only units in the same network as user may be accessed. user network based on last login.
  #     only logged in users may view units regardless of value of privacy variable
  localization_type: network

  # dissemination
  #   true: updates / context-changes will be delivered to clients in users table
  #   false: no updates will be sent to clients
  dissemination: false

  # dissemination type
  #   selection:
  #     selection-based -- all changes will will be sent to selected users or clients
  #     selected users = users with subscriber attribute == true
  #   flood: selected entity changes will be sent to all users or clients
  dissemination_type: flood

  # flood_options
  #   array of entities whos changes will be will be sent to user
  #   ["unit", "item", "property", "log", "document", "location", "subunit", "checkin", "user"]
  flood_options: ["unit", "item", "property", "log", "document"]

  # filter types
  # if dissemination == true
  #   change-based
  #   time-based
  change_base: false
  time_base: false

  # update_frequency
  # if filter_type: time
  #   update_frequency: in minutes
  update_frequency: 10

  # locations
  #   true: allow user
  #   false: only admin
  location_create: true
  location_destroy: false
  location_update: false

  # items
  #   true: allow user
  #   false: only admin
  item_create: true
  item_destroy: false
  item_update: false

  # units
  #   true: allow user
  #   false: only admin
  unit_create: true
  unit_destroy: false
  unit_update: false

  # properties
  #   true: allow user
  #   false: only admin
  properties_create: true
  properties_destroy: false
  properties_update: false

  # logs
  #   true: allow user
  #   false: only admin
  logs_create: true
  logs_destroy: false
  logs_update: false

  # documents
  #   true: allow user
  #   false: only admin
  docs_create: true
  docs_destroy: false
  docs_update: false
test:

production:
  # privacy
  #   true: units/items are available to logged in users only (token required)
  #   false:
  #       units/items where is_public == true are available to public (no token)
  #       locations are available to unregistered users
  #   custom:
  #       public units are available to unregistered users
  #       private units may be accessible to certain users based on user_access table
  #       locations are available to unregistered users
  privacy: true

  # localization
  #   true:
  #     only units in the same location/network as user may be accessed. user location/network based on last checkin/ last login ip.
  #     only logged in users may view units regardless of value of privacy variable
  #   false: units are visible regardless of user location
  localization: false


  # localization type
  #   location:
  #     only units in the same location as user may be accessed. user location based on last checkin.
  #     only logged in users may view units regardless of value of privacy variable
  #   network:
  #     only units in the same network as user may be accessed. user network based on last login.
  #     only logged in users may view units regardless of value of privacy variable
  localization_type: network

  # dissemination
  #   true: updates / context-changes will be delivered to clients in users table
  #   false: no updates will be sent to clients
  dissemination: true

  # dissemination type
  #   selection:
  #     selection-based -- all changes will will be sent to selected users or clients
  #     selected users = users with subscriber attribute == true
  #   flood: selected entity changes will be sent to all users or clients
  dissemination_type: flood

  # flood_options
  #   array of entities whos changes will be will be sent to user
  #   ["unit", "item", "property", "log", "document", "location", "subunit", "checkin", "user"]
  flood_options: ["unit", "item", "property", "log", "document"]

  # filter_type
  # if dissemination == true
  #   change: change-based
  #   time: time-based
  filter_type: change

  # update_frequency
  # if filter_type: time
  #   update_frequency: in minutes
  update_frequency: 10

  # locations
  #   true: allow user
  #   false: only admin
  location_create: true
  location_destroy: false
  location_update: false

  # items
  #   true: allow user
  #   false: only admin
  item_create: true
  item_destroy: false
  item_update: false

  # units
  #   true: allow user
  #   false: only admin
  unit_create: true
  unit_destroy: false
  unit_update: false

  # properties
  #   true: allow user
  #   false: only admin
  properties_create: true
  properties_destroy: false
  properties_update: false

  # logs
  #   true: allow user
  #   false: only admin
  logs_create: true
  logs_destroy: false
  logs_update: false

  # documents
  #   true: allow user
  #   false: only admin
  docs_create: true
  docs_destroy: false
  docs_update: false

